name: Deploy to Vercel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: npm i -g vercel

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.y3BMmZkbjOdhEP0ZWhKw0vCr }} --prod
      env:
        VERCEL_ORG_ID: ${{ secrets.team_0joWeyNvRJFRIe48YErmRYgZ }}
        VERCEL_PROJECT_ID: ${{ secrets.prj_JopA0RnOVnpmoX4iuMaezpkqztYF }}
